export const FONT_OPTIONS = [
  { label: 'Arial', value: "Arial, 'Helvetica Neue', Helvetica, sans-serif" },
  { label: 'Arial Black', value: "'Arial Black', 'Arial Bold', Gadget, sans-serif" },
  { label: 'Book Antiqua', value: "'Book Antiqua', Palatino, 'Palatino Linotype', 'Palatino LT STD', Georgia, serif" },
  { label: 'Brush Script', value: "'Brush Script MT', cursive" },
  { label: 'Calibri', value: "Calibri, Candara, Segoe, 'Segoe UI', Optima, Arial, sans-serif" },
  { label: 'Cambria', value: "Cambria, Georgia, serif" },
  { label: 'Candara', value: "Candara, Calibri, Segoe, 'Segoe UI', Optima, Arial, sans-serif" },
  { label: 'Century Gothic', value: "'Century Gothic', AppleGothic, sans-serif" },
  { label: 'Century Schoolbook', value: "'Century Schoolbook', 'New Century Schoolbook', 'L049003L', serif" },
  { label: 'Comic Sans MS', value: "'Comic Sans MS', cursive" },
  { label: 'Consolas', value: "Consolas, monaco, monospace" },
  { label: 'Constantia', value: "Constantia, Lucidabright, 'Lucidabright Regular', 'Lucida Bright', Lucida, 'DejaVu Serif', 'Bitstream Vera Serif', 'Liberation Serif', Georgia, serif" },
  { label: 'Copperplate', value: "Copperplate, 'Copperplate Gothic Light', sans-serif" },
  { label: 'Corbel', value: "Corbel, 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', 'DejaVu Sans', 'Bitstream Vera Sans', 'Liberation Sans', Verdana, 'Verdana Ref', sans-serif" },
  { label: 'Courier New', value: "'Courier New', Courier, 'Lucida Sans Typewriter', 'Lucida Typewriter', monospace" },
  { label: 'Edwardian Script', value: "'Edwardian Script ITC', cursive" },
  { label: 'Franklin Gothic', value: "'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif" },
  { label: 'French Script', value: "'French Script MT', cursive" },
  { label: 'Garamond', value: "Garamond, Baskerville, 'Baskerville Old Face', 'Hoefler Text', 'Times New Roman', serif" },
  { label: 'Georgia', value: "Georgia, Times, 'Times New Roman', serif" },
  { label: 'Gill Sans', value: "'Gill Sans', 'Gill Sans MT', Calibri, sans-serif" },
  { label: 'Goudy Old Style', value: "'Goudy Old Style', Garamond, 'Big Caslon', 'Times New Roman', serif" },
  { label: 'Helvetica', value: "'Helvetica Neue', Helvetica, Arial, sans-serif" },
  { label: 'Impact', value: "Impact, Haettenschweiler, 'Franklin Gothic Bold', Charcoal, 'Helvetica Inserat', 'Bitstream Vera Sans Bold', 'Arial Black', sans-serif" },
  { label: 'Lucida Console', value: "'Lucida Console', 'Lucida Sans Typewriter', Monaco, 'Bitstream Vera Sans Mono', monospace" },
  { label: 'Lucida Handwriting', value: "'Lucida Handwriting', cursive" },
  { label: 'Lucida Sans', value: "'Lucida Sans Unicode', 'Lucida Grande', sans-serif" },
  { label: 'Mistral', value: "Mistral, cursive" },
  { label: 'MS Verdana', value: "Verdana, Geneva, sans-serif" },
  { label: 'MT Segoe Script', value: "'MT Segoe Script', cursive" },
  { label: 'Palatino', value: "Palatino, 'Palatino Linotype', 'Palatino LT STD', 'Book Antiqua', Georgia, serif" },
  { label: 'Papyrus', value: "Papyrus, 'Comic Sans MS', cursive" },
  { label: 'Perpetua', value: "Perpetua, Baskerville, 'Big Caslon', 'Palatino Linotype', Palatino, 'URW Palladio L', 'Nimbus Roman No9 L', serif" },
  { label: 'Rockwell', value: "Rockwell, 'Courier Bold', Courier, Georgia, Times, 'Times New Roman', serif" },
  { label: 'Segoe UI', value: "'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif" },
  { label: 'Tahoma', value: "Tahoma, Verdana, Segoe, sans-serif" },
  { label: 'Times New Roman', value: "'Times New Roman', Times, Baskerville, Georgia, serif" },
  { label: 'Trebuchet', value: "'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif" },
];
